apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digitalmydomain-xyz-certificate
  namespace: default
spec:
  secretName: digitalmydomain-xyz-tls
  dnsNames:
    - digitalmydomain.xyz
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
