apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        azureDNS:
          clientID: YOUR_AZURE_CLIENT_ID
          clientSecretSecretRef:
            name: azuredns-client-secret
            key: clientSecret
          subscriptionID: YOUR_AZURE_SUBSCRIPTION_ID
          tenantID: YOUR_AZURE_TENANT_ID
          resourceGroupName: YOUR_AZURE_RESOURCE_GROUP
          hostedZoneName: digitalmydomain.xyz